config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :sale_details
  resources :sales 
  resources :clients
  resources :products

  get 'main/index'

  get "logout" => "sessions#destroy", :as => "logout"  
  get "login" => "sessions#new", :as => "login"  
  get "signup" => "users#new", :as => "signup"

  resources :sessions
  
  root :to => "sessions#new"

end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :sales, :dependent => :destroy
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @per_page = 5
    @clients = Client.paginate(per_page: @per_page, page: params[:page])
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to :clients, notice: 'Cliente Creado Satisfactoriamente' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: :clients.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to :clients, notice: 'Cliente Actualizado Correctamente' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy    
    @client = Client.find(params[:id])
    @client.destroy
    respond_to do |format|
      format.html { redirect_to :clients }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:cedula, :nombres, :direccion, :telefono, :correo)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_clients.html.erb
<div class="row">
  <div class="col-xs-12">              
    <div class="box">
      <div class="box-header text-center">
        <h3 class="box-title">Lista de Clientes</h3>
      </div><!-- /.box-header -->
      <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
          <thead>
            <tr>
              <th>Cedula</th>
              <th>Nombres</th>
              <th>Direccion</th>
              <th>Telefono</th>
              <th>Correo</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <% @clients.each do |client| %>
          <tbody>
            <tr>
              <td><%= client.cedula %></td>
              <td><%= client.nombres %></td>
              <td><%= client.direccion %></td>
              <td><%= client.telefono %></td>
              <td><%= client.correo %></td>
              <td><%= link_to '<i class= "fa fa-pencil fa-2x"></i>'.html_safe, edit_client_path(client), class: 'btn btn-social-icon btn-tumblr'  %>
              <%= button_to  client_path(client), method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, class: 'btn btn-social-icon btn-tumblr borrar_cliente' do  %>
              <i class= "fa fa-trash fa-2x"></i>
              <%end%>    
              </td>
            </tr>           
          </tbody>
          <% end %>
          <%= will_paginate @clients, previous_label: "Anterior", next_label: "Siguiente", class: 'flickr_pagination pull-right '%>                   
        </table>
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div><!-- /.col -->
</div><!-- /.row -->

app/views/clients/_form.html.erb
<div class="col-md-4">
<div class="form-group">
<%= f.label :cedula %>*<br>
<%= f.text_field :cedula, class: 'form-control', placeholder: 'Cedula del cliente' %>
</div>
<div class="form-group">
<%= f.label :nombres %>*<br>
<%= f.text_field :nombres, class: 'form-control', placeholder: 'Nombre del cliente' %>
</div>
<div class="form-group">
<%= f.label :direccion %><br>
<%= f.text_field :direccion, class: 'form-control', placeholder: 'Direccion del cliente' %>
</div>
<div class="form-group">
<%= f.label :telefono %><br>
<%= f.text_field :telefono, class: 'form-control', placeholder: 'Telefono del Cliente' %>
</div>
<div class="form-group">
<%= f.label :correo %><br>
<%= f.text_field :correo, class: 'form-control', placeholder: 'Correo del Cliente' %>
</div>
</div>

app/views/clients/edit.html.erb
<%content_for :stylesheet do%>
<%=stylesheet_link_tag "app"%>
<%end%>
<%= render 'menu/menu'%>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
  <section class="content-header">
    <ol class="breadcrumb">
      <li>
		<%= link_to "<i class='fa fa-user-plus'></i> Clientes".html_safe, :clients %>
      </li>
      <li class="active">Editar</li>
    </ol>
  </section>
    <!-- Main content -->
  <section class="content">
  <% flash.each do |name, msg| %>  
    <%= content_tag :div, msg, :id => "flash_#{name}" %>    
  <% end %>
	<%=form_for @client do |f|%>
		<div class="row">
			<div class="col-md-3"></div>
			<%=render 'form', f: f%>
  	</div>
  	<div class="text-center">
  		<div class="form-group">
    	<%= f.submit "Editar", class: 'btn btn-app bg-olive' %>    	
  		</div>
  	</div>
 	<%end%>  
  </section><!-- /.content -->
</div><!-- /.content-wrapper -->
<%= render 'menu/footer'%>
<% content_for :javascript do %>
<%=javascript_include_tag "clients.js"%>
<%=javascript_include_tag "jquery.validate.min.js"%>
<%end%>

app/views/clients/index.html.erb
<%content_for :stylesheet do%>
<%=stylesheet_link_tag "app"%>
<%end%>
<%= render 'menu/menu'%>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
  <section class="content-header">
    <ol class="breadcrumb" id="miniguia">
      <li>
        <%= link_to "<i class='fa fa-user-plus'></i> Clientes".html_safe, :clients, id:'submenu' %>
      </li>
      <li class="active" id="submenu2">Index</li>
    </ol>
  </section>
    <!-- Main content -->
  <section class="content">
  <% flash.each do |name, msg| %>
 <div class="alert alert-success alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
     <h4>  <i class="icon fa fa-check"></i><%= msg %></h4>
  </div>
  <% end %>
  <%= link_to "<i class='fa fa-users'></i> Nuevo Cliente".html_safe, new_client_path, class: 'btn btn-app', id: 'btn-nuevo'%>
  <%= render 'clients'%>  
  </section><!-- /.content -->
</div><!-- /.content-wrapper -->
<%= render 'menu/footer'%>
<% content_for :javascript do %>
<%=javascript_include_tag "jquery.validate.min.js"%>
<%=javascript_include_tag "clients"%>
<%end%>

app/views/clients/new.html.erb
<%content_for :stylesheet do%>
<%=stylesheet_link_tag "app"%>
<%end%>
<%= render 'menu/menu'%>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
  <section class="content-header">
    <ol class="breadcrumb">
      <li>
        <%= link_to "<i class='fa fa-user-plus'></i> Clientes".html_safe, :clients %>
      </li>
      <li class="active">Nuevo</li>
    </ol>
  </section>
    <!-- Main content -->
  <section class="content">
  <% flash.each do |name, msg| %>  
    <%= content_tag :div, msg, :id => "flash_#{name}" %>    
  <% end %>
	<%=form_for @client do |f|%>
		<div class="row">
			<div class="col-md-3"></div>
			<%=render 'form', f: f%>
  	</div>
  	<div class="text-center">
  		<div class="form-group">
    			<%= f.submit "Agregar", class: 'btn btn-app', id: 'btn-formu' %>
  		</div>
  	</div>
 	<%end%>  
  </section><!-- /.content -->
</div><!-- /.content-wrapper -->
<%= render 'menu/footer'%>
<% content_for :javascript do %>
<%=javascript_include_tag "clients"%>
<%=javascript_include_tag "jquery.validate.min.js"%>

<%end%>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cedula:</strong>
  <%= @client.cedula %>
</p>

<p>
  <strong>Nombres:</strong>
  <%= @client.nombres %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @client.direccion %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @client.telefono %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @client.correo %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>