config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :sale_details
  resources :sales 
  resources :clients
  resources :products

  get 'main/index'

  get "logout" => "sessions#destroy", :as => "logout"  
  get "login" => "sessions#new", :as => "login"  
  get "signup" => "users#new", :as => "signup"

  resources :sessions
  
  root :to => "sessions#new"

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :client
  belongs_to :user
  has_many :sale_details, :dependent => :destroy
  #callbacks
  before_save :add_total
  private
  def add_total
  	iva = (self.subtotal.nil? ? 0 : self.subtotal) * 0.16
  	self.total = (self.subtotal.nil? ? 0 : self.subtotal) + iva
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]
=begin
  Pendientes
  1 - SACAR PRODUCTOS YA AGREGADOS en el Create
  2 - CARGAR PRODUCTOS EN EL EDIT CUANDO SE REALIZE EL FILTRO DEL CREATE
=end
  # GET /sales
  # GET /sales.json
  def index
    @per_page = 5
    @sales = Sale.paginate(per_page: @per_page, page: params[:page])
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @per_page = 5
    @sale_details = SaleDetail.where(sale_id: @sale.id).paginate(per_page: @per_page, page: params[:page])
     
    @sale_detail = SaleDetail.new
    @products = Product.all
    @sale = Sale.find(params[:id])
    respond_to do |format|      
      format.html{ render :show }
      format.json{
        render json: @sale, status: :ok
      }
      format.xlsx {
        #AGREgar excel
        @sale_details = SaleDetail.where(sale_id: @sale.id).paginate(per_page: @per_page, page: params[:page])
        render xlsx: "show", disposition: "attachment", filename: "Venta_No_#{@sale.id}.xlsx"
      }
      format.pdf {
        render pdf: "Venta",
        layout: "application",
        print_media_type: true,
       disposition: "attachment"
      }
    end
  end

  # GET /sales/new
  def new
    @sale = Sale.new
    @clients = Client.all
  end

  # GET /sales/1/edit
  def edit
    @clients = Client.all
  end

  # POST /sales
  # POST /sales.json
  def create
    cliente = Client.find(sale_params[:client_id])
    temp = sale_params
    temp["client_id"] = cliente.id
    @sale = Sale.new(temp)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to :sales, notice: 'Venta Creada' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to :sales, notice: 'Venta Actualizada' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
   @sale = Sale.find(params[:id])
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to :sales }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:fecha, :subtotal, :total, :client_id, :user_id, :estado)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_details.html.erb
<div class="row">
  <div class="col-xs-12">              
    <div class="box">
      <div class="box-header text-center">
        <h3 class="box-title">Lista de Articulos</h3>
      </div><!-- /.box-header -->
      <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
          <thead>
            <tr>
              <th>Producto</th>
              <th>Precio</th>
              <th>Cantidad</th>
              <th>Sub Total</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <% @sale_details.each do |detail| %>
            <tbody>
              <tr>
                <td><%= detail.product.nombre %></td>
                <td><%= number_to_currency(detail.product.precio) %></td>
                <td><%= detail.cantidad %></td>
                <td><%= number_to_currency(detail.total) %></td>
                <td>
                  <button type='button' id='edit-sale-detail-<%=detail.id%>'class='btn btn-social-icon btn-tumblr edit-sale-details' data-toggle="modal" data-target="#edit-details"> <span class='fa fa-pencil-square-o'></span> </button>
                  <%= button_to  sale_detail_path(detail), method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, class: 'btn btn-social-icon btn-tumblr borrar_detalle' do  %>
                    <i class= "fa fa-trash fa-2x"></i>
                  <%end%>
                </td>
              </tr>           
            </tbody>
          <% end %>
          <%= will_paginate @sale_details, previous_label: "Anterior", next_label: "Siguiente", class: 'flickr_pagination pull-right '%>                       
        </table>
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div><!-- /.col -->
</div><!-- /.row -->

app/views/sales/_form.html.erb
<div class="col-md-4">
  <div class="form-group">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha%>
  </div>
  <div class="form-group">
    <%= f.label :client_id, 'Cliente' %><br>
    <%=f.select :client_id, options_from_collection_for_select(@clients, 'id', 'nombres'),{}, {class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.label :user_id, 'Usuario' %><br>
    <%= f.hidden_field :user_id, value: current_user.id%>
    <%=text_field_tag 'nombre', nil, value: current_user.nombres, disabled: true, class: 'form-control'%>
  </div>
</div>

app/views/sales/_sales.html.erb
<div class="row">
  <div class="col-xs-12">              
    <div class="box">
      <div class="box-header text-center">
        <h3 class="box-title">Lista de Articulos</h3>
      </div><!-- /.box-header -->
      <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
          <thead>
            <tr>
              <th>Cliente</th>
              <th>Usuario</th>
              <th>Fecha</th>
              <th>Subtotal</th>
              <th>Total</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <% @sales.each do |sale| %>
            <tbody>
              <tr>
                <td><%= sale.client.nombres %></td>
                <td><%= sale.user.nombres %></td>
                <td><%= (sale.fecha).strftime("%d/%m/%Y") %></td>
                <td><%= number_to_currency(sale.subtotal.nil? ? 0 : sale.subtotal) %></td>
                <td><%= number_to_currency(sale.total.nil? ? 0 : sale.total) %></td>
                <td>
                  <%= link_to '<i class= "fa fa-eye"></i>'.html_safe, (sale),class: 'btn btn-social-icon btn-tumblr' %>
                  <%= link_to '<i class= "fa fa-pencil"></i>'.html_safe, edit_sale_path(sale),class: 'btn btn-social-icon btn-tumblr' %>
                  <%= link_to '<i class= "fa fa-file-excel-o"></i>'.html_safe, sale_path(sale, format: :xlsx),class: 'btn btn-social-icon btn-tumblr' %>
                  <%= link_to '<i class= "fa fa-file-pdf-o"></i>'.html_safe, sale_path(sale, format: :pdf),class: 'btn btn-social-icon btn-tumblr' %>
                  <%= button_to  sale_path(sale), method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, class: 'btn btn-social-icon btn-tumblr borrar_venta' do  %>
                    <i class= "fa fa-trash fa-2x"></i>
                  <%end%>
                </td>
              </tr>           
            </tbody>
          <% end %>                   
        </table>
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div><!-- /.col -->
</div><!-- /.row -->

app/views/sales/edit.html.erb
<%content_for :stylesheet do%>
<%=stylesheet_link_tag "app"%>
<%end%>
<%= render 'menu/menu'%>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
  <section class="content-header">
    <ol class="breadcrumb" id="miniguia">
      <li>
        <%= link_to "<i class='fa fa-cart-plus'></i> Ventas".html_safe, :sales, id:'submenu' %>
      </li>
      <li class="active" id="submenu2">Editar</li>
    </ol>
  </section>
    <!-- Main content -->
  <section class="content">
  <% flash.each do |name, msg| %>  
    <%= content_tag :div, msg, :id => "flash_#{name}" %>    
  <% end %>
  <div class="box box-primary" id="panel">  
    <h1 class="text-center">Editar Venta</h1>
	<%=form_for @sale do |f|%>
		<div class="row">
			<div class="col-md-4"></div>
			<%=render 'form', f: f%>
  	</div>
  	<div class="text-center">
  		<div class="form-group">
    		<%= f.submit "Editar", class: 'btn btn-app', id:'btn-formu' %>
  		</div>
  	</div>
 	<%end%>
  </div>  
  </section><!-- /.content -->
</div><!-- /.content-wrapper -->
<%= render 'menu/footer'%>
<% content_for :javascript do %>
<%=javascript_include_tag "sales"%>
<%=javascript_include_tag "jquery.validate.min.js"%>

<%end%>

app/views/sales/index.html.erb
<%content_for :stylesheet do%>
  <%=stylesheet_link_tag "app"%>
<%end%>
<%= render 'menu/menu'%>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
  <section class="content-header">
    <ol class="breadcrumb" id="miniguia">
      <li>
        <%= link_to "<i class='fa fa-cart-plus'></i> Ventas".html_safe, :sales, id:'submenu' %>
      </li>
      <li class="active" id="submenu2">Index</li>
    </ol>
  </section>
    <!-- Main content -->
  <section class="content">
  <% flash.each do |name, msg| %>
 <div class="alert alert-success alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
     <h4>  <i class="icon fa fa-check"></i><%= msg %></h4>
  </div>
  <% end %>
  <%= link_to "<i class='fa fa-cart-plus'></i> Nueva Venta".html_safe, new_sale_path, class: 'btn btn-app', id: 'btn-nuevo'%>
  <%= render 'sales'%>  
  </section><!-- /.content -->
</div><!-- /.content-wrapper -->
<%= render 'menu/footer'%>
<% content_for :javascript do %>
  <%=javascript_include_tag "jquery.validate.min.js"%>
  <%=javascript_include_tag "sales"%>
<%end%>

app/views/sales/new.html.erb
<%content_for :stylesheet do%>
<%=stylesheet_link_tag "app"%>
<%end%>
<%= render 'menu/menu'%>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
  <section class="content-header">
    <ol class="breadcrumb" id="miniguia">
      <li>
        <%= link_to "<i class='fa fa-cart-plus'></i> Ventas".html_safe, sales_path, id:'submenu' %>
      </li>
      <li class="active" id="submenu2">Nuevo</li>
    </ol>
  </section>
    <!-- Main content -->
  <section class="content">
  <% flash.each do |name, msg| %>  
    <%= content_tag :div, msg, :id => "flash_#{name}" %>    
  <% end %>
  <div class="box box-primary" id="panel">  
    <h1 class="text-center">Generar Venta</h1>
	<%=form_for @sale do |f|%>
		<div class="row">
			<div class="col-md-4"></div>
			<%=render 'form', f: f%>
  	</div>
  	<div class="text-center">
  		<div class="form-group">
    		<%= f.submit "Agregar", class: 'btn btn-app', id:'btn-formu' %>
  		</div>
  	</div>
 	<%end%>
  </div>  
  </section><!-- /.content -->
</div><!-- /.content-wrapper -->
<%= render 'menu/footer'%>
<% content_for :javascript do %>
<%=javascript_include_tag "sales"%>
<%=javascript_include_tag "jquery.validate.min.js"%>

<%end%>

app/views/sales/show.html.erb
<%content_for :stylesheet do%>
<%=stylesheet_link_tag "app"%>
<%end%>
<%= render 'menu/menu'%>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
  <section class="content-header">
    <ol class="breadcrumb" id="miniguia">
      <li>
        <%= link_to "<i class='fa fa-cart-plus'></i> Ventas".html_safe, :sales, id:'submenu' %>
      </li>
      <li class="active" id="submenu2">Detalle</li>
    </ol>
  </section>
    <!-- Main content -->
  <section class="content">
  <% flash.each do |name, msg| %>
 <div class="alert alert-success alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
     <h4>  <i class="icon fa fa-check"></i><%= msg %></h4>
  </div>
  <% end %>
<br><br>
  <section class="invoice">
    <!-- title row -->
    <div class="row">
      <div class="col-xs-12">
        <h2 class="page-header">
          <i class="fa fa-money "></i> Venta No° <%=@sale.id%>.
          <small class="pull-right"><b>Fecha: <%=(@sale.fecha).strftime("%d/%m/%Y")%></b></small>
        </h2>
      </div><!-- /.col -->
    </div>
    <!-- info row -->
    <div class="row invoice-info">
      <div class="col-sm-4 invoice-col text-center">
        <address>
          <strong>Cliente</strong><br>
          <b>C.C.</b> <%= @sale.client.cedula %><br>
          <b>Nombre: </b><%= @sale.client.nombres %><br>
          <b>Direccion: </b><%= @sale.client.direccion %><br>
          <b>Telefono: </b><%= @sale.client.telefono %><br>
          <b>Correo: </b><%= @sale.client.correo %>
        </address>
      </div><!-- /.col -->
      <div class="col-sm-2 invoice-col text-center">
        <address>
          <strong>Vendedor</strong><br>
          <%= @sale.user.nombres %> <br>
        </address>
      </div><!-- /.col -->
      <div class="col-sm-3 invoice-col text-center">
        <b>SubTotal: </b> <%= number_to_currency(@sale.subtotal.nil? ? 0 : @sale.subtotal) %><br>
        <b>Total: </b> <%= number_to_currency(@sale.total.nil? ? 0 : @sale.total) %><br>
      </div><!-- /.col -->
      <div class="col-sm-2 invoice-col text-center">
          <button id="btn-nuevo" type="button" class="btn btn-app" data-toggle="modal" data-target="#add-detail"><i class='fa fa-cart-plus'></i> Detalle Venta</button>
      </div>
    </div><!-- /.row -->

    <!-- Table row -->
    <div class="row">
      <div class="col-xs-12 table-responsive">
        <%= render 'details'%>  
      </div><!-- /.col -->
    </div><!-- /.row -->
  </section><!-- /.content -->
</div><!-- /.content-wrapper -->
<%= render 'menu/footer'%>
<% content_for :javascript do %>
  <%=javascript_include_tag "jquery.validate.min.js"%>
  <%=javascript_include_tag "sales"%>
<%end%>
<div id="add-detail" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Agregar Detalle</h4>
      </div>
      <div class="modal-body">
      <%= form_for(@sale_detail) do |f| %>
          <%= f.hidden_field :sale_id, value: @sale.id %>
        <div class="form-group">
          <label for="inputPassword3" class="col-sm-2 control-label">Producto</label>
          <div class="col-sm-10">
            <%= f.select :product_id ,options_from_collection_for_select(@products,'id','nombre', @sale_detail.product.nil? ? nil : @budget_sub_category.product.id),{},{class: 'form-control'}%>
          </div>
        </div>
        <br>
        <div class="form-group">
          <label for="inputPassword3" class="col-sm-2 control-label">Cantidad</label>
          <div class="col-sm-6">
            <%= f.number_field :cantidad, placeholder: 'Digite la Cantidad', class: 'form-control' %>
          </div>
        </div>
        <br><br>
      </div>
      <div class="modal-footer">
          <%= f.submit 'Agregar', class: 'btn btn-default' %>
      <% end %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>

  </div>
</div>
<div id="edit-details" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Agregar Detalle</h4>
      </div>
      <div class="modal-body">
      <%= form_for @sale_detail, format: :json, remote: true, method: :put, html: {id: 'edit_sale_detail', class: 'edit_sale_detail'} do |f| %>
          <%= f.hidden_field :sale_id, value: @sale.id %>
        <div class="form-group">
          <label for="inputPassword3" class="col-sm-2 control-label">Producto</label>
          <div class="col-sm-10">
            <%=select_tag('sale_detail[product_id]', options_from_collection_for_select(@products,'id','nombre', @sale_detail.product.nil? ? nil : @budget_sub_category.product.id), id: 'edit_product') %>
          </div>
        </div>
        <br>
        <div class="form-group">
          <label for="inputPassword3" class="col-sm-2 control-label">Cantidad</label>
          <div class="col-sm-6">
            <%= f.number_field :cantidad, placeholder: 'Digite la Cantidad', class: 'form-control', id: 'edit_cantidad' %>
          </div>
        </div>
        <br><br>
      </div>
      <div class="modal-footer">
          <%= f.submit 'Agregar', class: 'btn btn-default' %>
      <% end %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/sales/show.pdf.erb
<%content_for :stylesheet do%>
  <%= wicked_pdf_stylesheet_link_tag "app" %>
  <%=wicked_pdf_stylesheet_link_tag "_all-skins.min.css"%>
  <%=wicked_pdf_stylesheet_link_tag "AdminLTE.css"%>
  <%=wicked_pdf_stylesheet_link_tag "bootstrap.css"%>

<%end%>
<div class="content-wrapper">
    <!-- Main content -->
  <section class="content">
  <% flash.each do |name, msg| %>
 <div class="alert alert-success alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
     <h4>  <i class="icon fa fa-check"></i><%= msg %></h4>
  </div>
  <% end %>
<br><br>
  <section class="invoice">
    <!-- title row -->
    <div class="row">
      <div class="col-xs-12">
        <h2 class="page-header">
          <i class="fa fa-money "></i> Venta No <%=@sale.id%>.
          <small class="pull-right"><b>Fecha: <%=(@sale.fecha).strftime("%d/%m/%Y")%></b></small>
        </h2>
      </div><!-- /.col -->
    </div>
    <!-- info row -->
    <div class="row invoice-info">
      <div class="col-sm-4 invoice-col text-center">
        <address>
          <strong>Cliente</strong><br>
          <b>C.C.</b> <%= @sale.client.cedula %><br>
          <b>Nombre: </b><%= @sale.client.nombres %><br>
          <b>Direccion: </b><%= @sale.client.direccion %><br>
          <b>Telefono: </b><%= @sale.client.telefono %><br>
          <b>Correo: </b><%= @sale.client.correo %>
        </address>
      </div><!-- /.col -->
      <div class="col-sm-2 invoice-col text-center">
        <address>
          <strong>Vendedor</strong><br>
          <%= @sale.user.nombres %> <br>
        </address>
      </div><!-- /.col -->
      <div class="col-sm-3 invoice-col text-center">
        <b>SubTotal: </b> <%= number_to_currency(@sale.subtotal.nil? ? 0 : @sale.subtotal) %><br>
        <b>Total: </b> <%= number_to_currency(@sale.total.nil? ? 0 : @sale.total) %><br>
      </div><!-- /.col -->
    </div><!-- /.row -->

    <!-- Table row -->
    <div class="row">
      <div class="col-xs-12 table-responsive">
        <div class="row">
          <div class="col-xs-12">              
            <div class="box">
              <div class="box-header text-center">
                <h3 class="box-title">Lista de Articulos</h3>
              </div><!-- /.box-header -->
              <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th class="text-center">Producto</th>
                      <th class="text-center">Precio</th>
                      <th class="text-center">Cantidad</th>
                      <th class="text-center">Sub Total</th>
                    </tr>
                  </thead>
                  <% @sale_details.each do |detail| %>
                    <tbody>
                      <tr>
                        <td><%= detail.product.nombre %></td>
                        <td><%= number_to_currency(detail.product.precio) %></td>
                        <td><%= detail.cantidad %></td>
                        <td><%= number_to_currency(detail.total) %></td>
                      </tr>           
                    </tbody>
                  <% end %>            
                </table>
              </div><!-- /.box-body -->
            </div><!-- /.box -->
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.col -->
    </div><!-- /.row -->
  </section><!-- /.content -->
</div><!-- /.content-wrapper -->
<% content_for :javascript do %>
  <%=javascript_include_tag "jquery.validate.min.js"%>
  <%=javascript_include_tag "sales"%>
<%end%>