config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :sale_details
  resources :sales 
  resources :clients
  resources :products

  get 'main/index'

  get "logout" => "sessions#destroy", :as => "logout"  
  get "login" => "sessions#new", :as => "login"  
  get "signup" => "users#new", :as => "signup"

  resources :sessions
  
  root :to => "sessions#new"

end

app/models/sale_detail.rb
class SaleDetail < ActiveRecord::Base
  belongs_to :sale
  belongs_to :product
  #callBacks
  after_save :calcular_total
  before_save :add_sub_total
  before_destroy :eliminar_total
  private
  def add_sub_total
  	self.total =  (self.product.precio.nil? ? 0 : self.product.precio) * (self.cantidad.nil? ? 0 : self.cantidad)
  end
  def calcular_total
  	temp = self.sale.sale_details.sum(total)
  	self.sale.subtotal = temp
  	self.sale.save
  end
  def eliminar_total
  	temp = self.sale.subtotal - self.total
  	self.sale.subtotal = temp
  	self.sale.save
  end
end

app/controllers/sale_details_controller.rb
class SaleDetailsController < ApplicationController
  before_action :set_sale_detail, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /sale_details
  # GET /sale_details.json
  def index
    @sale_details = SaleDetail.all
  end

  # GET /sale_details/1
  # GET /sale_details/1.json
  def show
  end

  # GET /sale_details/new
  def new
    @sale_detail = SaleDetail.new
  end

  # GET /sale_details/1/edit
  def edit
  end

  # POST /sale_details
  # POST /sale_details.json
  def create
    @sale_detail = SaleDetail.new(sale_detail_params)

    respond_to do |format|
      if @sale_detail.save
        format.html { redirect_to :back, notice: 'Detalle Agregado' }
        format.json { render :show, status: :created, location: @sale_detail }
      else
        format.html { render :new }
        format.json { render json: @sale_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sale_details/1
  # PATCH/PUT /sale_details/1.json
  def update
      if @sale_detail.update(sale_detail_params)
        redirect_to :back, notice: 'Detalle Editado'
      else
        render :edit 
      end
  end

  # DELETE /sale_details/1
  # DELETE /sale_details/1.json
  def destroy
    @sale_detail.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Registro Eliminado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale_detail
      @sale_detail = SaleDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_detail_params
      params.require(:sale_detail).permit(:sale_id, :product_id, :cantidad, :total)
    end
end

app/helpers/sale_details_helper.rb
module SaleDetailsHelper
end

app/views/sale_details/_form.html.erb
<%= form_for(@sale_detail) do |f| %>
  <div class="field">
    <%= f.label :sale_id %><br>
    <%= f.text_field :sale_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.text_field :total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sale_details/edit.html.erb
<h1>Editing Sale Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale_detail %> |
<%= link_to 'Back', sale_details_path %>

app/views/sale_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sale Details</h1>

<table>
  <thead>
    <tr>
      <th>Sale</th>
      <th>Product</th>
      <th>Cantidad</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sale_details.each do |sale_detail| %>
      <tr>
        <td><%= sale_detail.sale %></td>
        <td><%= sale_detail.product %></td>
        <td><%= sale_detail.cantidad %></td>
        <td><%= sale_detail.total %></td>
        <td><%= link_to 'Show', sale_detail %></td>
        <td><%= link_to 'Edit', edit_sale_detail_path(sale_detail) %></td>
        <td><%= link_to 'Destroy', sale_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale detail', new_sale_detail_path %>

app/views/sale_details/new.html.erb
<h1>New Sale Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', sale_details_path %>

app/views/sale_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sale:</strong>
  <%= @sale_detail.sale %>
</p>

<p>
  <strong>Product:</strong>
  <%= @sale_detail.product %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @sale_detail.cantidad %>
</p>

<p>
  <strong>Total:</strong>
  <%= @sale_detail.total %>
</p>

<%= link_to 'Edit', edit_sale_detail_path(@sale_detail) %> |
<%= link_to 'Back', sale_details_path %>